name: ingest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bokeh=2.4.3
  - bounded-pool-executor=0.0.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cachetools=5.2.0
  - cdsapi=0.5.1
  - certifi=2022.6.15
  - cffi=1.15.1
  - cftime=1.6.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.1.0
  - colorama=0.4.5
  - cryptography=37.0.1
  - curl=7.83.1
  - cytoolz=0.12.0
  - dask=2022.8.1
  - dask-core=2022.8.1
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.8.1
  - entrypoints=0.4
  - executing=1.0.0
  - flit-core=3.7.1
  - freetype=2.12.1
  - frozenlist=1.3.1
  - fsspec=2022.8.2
  - google-api-core=2.8.2
  - google-auth=2.11.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.5.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.4
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.15.0
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.1
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libprotobuf=3.21.5
  - libsodium=1.0.18
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.12
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=4.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - nbclient=0.6.7
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.0
  - notebook=6.4.12
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=3.0.5
  - packaging=21.3
  - pandas=1.4.4
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - pqdm=0.1.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - protobuf=4.21.5
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.9
  - pytz=2022.2.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=23.2.1
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - rsa=4.9
  - send2trash=1.8.0
  - setuptools=65.3.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.5.0
  - tblib=1.7.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - xarray=2022.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.8.1
  - zstd=1.5.2
